Exit uartmode if pppd returns a value that's 2 or higher.

diff --git a/uartmode b/uartmode
--- a/uartmode
+++ b/uartmode
@@ -42,6 +42,11 @@ if [ "$1" == "1" ]; then
 
 					echo 1 > /proc/sys/net/ipv4/ip_forward
 					taskset 1 pppd $conn_speed file /tmp/ppp_options
+					status=$?
+					if [ $status -gt 1 ]; then
+						echo "pppd exited on error $status"
+						exit 0
+					fi
 				else
 					echo "skip pppd"
 					exit 0
