PPPD respawn logic (#15)
* Exit uartmode if pppd returns a value that's 2 or higher.

* Allow all non-internal error codes to reboot pppd.

diff --git a/uartmode b/uartmode
--- a/uartmode
+++ b/uartmode
@@ -38,6 +38,10 @@ if [ "$1" == "1" ]; then
 
 					echo 1 > /proc/sys/net/ipv4/ip_forward
 					taskset 1 pppd $conn_speed file /tmp/ppp_options
+					status=$?
+					case $status in
+						1|2|3|4|6|7|9|137) echo "pppd exited with fatal error $status"; exit 0;;
+					esac
 				else
 					echo "skip pppd"
 					exit 0
